FROM frolvlad/alpine-oraclejdk8:slim
VOLUME /tmp
ADD police-0.0.1-SNAPSHOT.jar police.jar
RUN sh -c 'touch /police.jar'
ENV JAVA_OPTS=""
ENTRYPOINT [ "sh", "-c", "java $JAVA_OPTS -Djava.security.egd=file:/dev/./urandom -jar /police.jar" ]
